### ISSUE TITLE
Не безопасное удаление файла

### ISSUE THREAD

**Issue by Rid-lin** [constantinekg/pcpo#1]
Файл - pcpo/doc/INSTALL.txt
строчка 35 (sudo rm /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default)

Как-то не правильно выглядит...
Без предупреждения, и без создания резервной копии удалять файл настройки это явно не бест практикс.
Да и в документации нет информации о том что один из файлов конфигурации nginx будет удалён.
Что автоматически исключает установку на боевую машину.

**Comment by constantinekg** [comment]
Согласен, сейчас подправлю, сделаем бэкап на всякий...
